### PR TITLE
Add all contributors information

### PR DESCRIPTION
**Pull request by bryanlb**
###  Summary

Adds https://allcontributors.org/ to the project for recognizing folks that have contributed, via code or other contributions.

### CODE REVIEW

**Review by vthacker — APPROVED** [review]

**Comment by bryanlb** [comment]
@all-contributors
please add @bryanlb for code, doc, review, bug
please add @vthacker for code, doc, review, bug
please add @kyle-sammons for plugin, code

**Comment by bryanlb** [comment]
@all-contributors
please add @bryanlb for code, doc, review, bug.
please add @vthacker for code, doc, review, bug.
please add @kyle-sammons for plugin, code.

**Comment by bryanlb** [comment]
@allcontributors please add @vthacker for code, doc, review, bug.

**Comment by bryanlb** [comment]
@allcontributors please add @mansu for code, review, ideas, talk.

**Comment by bryanlb** [comment]
@allcontributors please add @ermontross for plugin

**Comment by bryanlb** [comment]
@allcontributors please add @danhermann for code

**Comment by bryanlb** [comment]
@allcontributors please add @slackhq for financial

**Comment by bryanlb** [comment]
@allcontributors please add @salesforce for financial

**Pull request merged**
